# Generated by Django 3.0.5 on 2021-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_auto_20210414_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('L', 'Liked'), ('D', 'Disliked'), ('N', 'No opinion')], max_length=1),
        ),
    ]
