# Generated by Django 3.0.5 on 2021-04-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_auto_20210414_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='liked',
            field=models.BooleanField(null=True),
        ),
    ]
