# Generated by Django 3.0.5 on 2021-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_auto_20210422_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='disliked',
            field=models.BooleanField(null=True),
        ),
    ]
