# Generated by Django 3.0.5 on 2021-05-11 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webApp', '0010_auto_20210425_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='book_user_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
