# Generated by Django 3.0.5 on 2021-05-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0011_book_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
    ]
